name: fcnd
channels:
    - conda-forge
dependencies:
    - python==3.6
    - numpy
    - matplotlib
    - jupyter
    - future
    - lxml
    - pip:
        - pymavlink>=2.2
        - utm>=0.4
        - websockets>=4.0.1
        - uvloop>=0.9.1
